version: "3.8"

services:
  pyro-sentry-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyro-sentry-api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
